version: '3.8'

services:

  tennis-db:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tennis_db
    ports:
      - "3306:3306"
    volumes:
      - type: volume
        source: tennis-volume
        target: /var/lib/mysql
      - type: bind
        source: ./initdb.d
        target: /docker-entrypoint-initdb.d
    networks:
      - sports-backend

  tennis-api:
    build: ./
    ports:
      - "49160:8080"
    networks:
      - sports-backend

volumes:
  tennis-volume:

networks:
  sports-backend:
    driver: bridge